name: Run Unit Tests and Linting, and Block Pull Request

on:
  pull_request:
    branches:
      - main  
  workflow_dispatch:  # Add workflow_dispatch to allow manual triggering

jobs:
  test-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Unit Tests
        run: python3 hangManUnitTest.py
        continue-on-error: true  # Continue even if tests fail, we'll check the status later

      - name: Run Linter
        run: pylint hangman.py
        continue-on-error: true  # Continue even if linting fails, we'll check the status later